name: Create Draft Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/**
      - apps/common
      - apps/project1
      - packages/**

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          cd apps/project1
          npm install

      - name: Get the current version
        id: get_version
        run: echo "::set-output name=version::$(node -p "require('./apps/project1/package.json').version")"

      - name: Bump version
        id: bump_version
        run: echo "::set-output name=new_version::$(node -e "const semver = require('semver'); const currentVersion = process.env.INPUT_VERSION; console.log(semver.inc(currentVersion, 'patch'))")"
        env:
          INPUT_VERSION: ${{ steps.get_version.outputs.version }}

      - name: Run semantic-release
        run: |
          cd apps/project1
          npx semantic-release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: apps/project1/*  # Include any artifacts or files you want to attach to the release
          tag_name: ${{ steps.bump_version.outputs.new_version }}
          title: Release ${{ steps.bump_version.outputs.new_version }}
          body: ${{ steps.bump_version.outputs.new_version }} Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
