name: Create Draft Release

on:
  push:
    branches:
      - main
    paths:
      - .github/**
      - apps/common
      - apps/project1
      - packages/**

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          cd  ./apps/project1
          npm ci

      - name: Get the latest tag
        id: get_tag
        run: echo "::set-output name=tag::$(git describe --tags --abbrev=0)"

      - name: Run semantic-release
        run: npx semantic-release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*  # Include any artifacts or files you want to attach to the release
          tag_name: ${{ steps.get_tag.outputs.tag }}
          title: Release ${{ steps.get_tag.outputs.tag }}
          body: ${{ steps.get_tag.outputs.tag }} Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}